name: Deploy UPM

on:
  push:
    branches: [ "workflow" ]

jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found # recreate the upm branch each time
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm                                            # checkout the branch
        git commit -am "upm update"
        git push -u origin upm --force                              # commit the branch

  release:
    name: create github release
    runs-on: ubuntu-latest
    needs: split-upm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: ${{ env.VERSION }}